--------------------------------------------------------
--  Fichier créé - mercredi-avril-15-2015   
--------------------------------------------------------
DROP TABLE "DARCIA"."ACTIVEB" cascade constraints;
DROP TABLE "DARCIA"."ANNEECOMPTABLE" cascade constraints;
DROP TABLE "DARCIA"."BUDGETPROJET" cascade constraints;
DROP TABLE "DARCIA"."CATEGORIEPROJET" cascade constraints;
DROP TABLE "DARCIA"."ELEMENTPLANMENSUEL" cascade constraints;
DROP TABLE "DARCIA"."GROUPES_UTILISATEUR" cascade constraints;
DROP TABLE "DARCIA"."LANGUE" cascade constraints;
DROP TABLE "DARCIA"."LIGNEBUDGET" cascade constraints;
DROP TABLE "DARCIA"."MESELEMENTSPLANSMENSUELS" cascade constraints;
DROP TABLE "DARCIA"."MESLIGNESBUDGETS" cascade constraints;
DROP TABLE "DARCIA"."MESMOIS" cascade constraints;
DROP TABLE "DARCIA"."MESPLANMENSUEL" cascade constraints;
DROP TABLE "DARCIA"."MESTHEMES" cascade constraints;
DROP TABLE "DARCIA"."MOIS" cascade constraints;
DROP TABLE "DARCIA"."MONNAIE" cascade constraints;
DROP TABLE "DARCIA"."OPERATIONBANQUE" cascade constraints;
DROP TABLE "DARCIA"."OPERATIONCAISSE" cascade constraints;
DROP TABLE "DARCIA"."PAYS" cascade constraints;
DROP TABLE "DARCIA"."PLANANNUEL" cascade constraints;
DROP TABLE "DARCIA"."PLANMENSUEL" cascade constraints;
DROP TABLE "DARCIA"."PRIVILEGESAPP" cascade constraints;
DROP TABLE "DARCIA"."PROJET" cascade constraints;
DROP TABLE "DARCIA"."SECTEURACTIVITE" cascade constraints;
DROP TABLE "DARCIA"."STRUCTURES" cascade constraints;
DROP TABLE "DARCIA"."TAB_PRIVILEGES" cascade constraints;
DROP TABLE "DARCIA"."THEMES" cascade constraints;
DROP TABLE "DARCIA"."UTILISATEURS" cascade constraints;
DROP TABLE "DARCIA"."VILLE" cascade constraints;
--------------------------------------------------------
--  DDL for Type T_ACTIVITEB
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_ACTIVITEB" AS object(
	libelle varchar(30),
	dateDebut date,
	dateFin date,
	montantPrevu number,
 	listRefLigneBudget t_listRefLigneBudget
 	);

/
--------------------------------------------------------
--  DDL for Type T_LISTREFLIGNEBUDGET
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_LISTREFLIGNEBUDGET" AS  TABLE  of t_refLigneBudget;

/
--------------------------------------------------------
--  DDL for Type T_ANNEECOMPTABLE
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_ANNEECOMPTABLE" AS object(
 	code varchar(30),
 	libelle varchar(30),
 	etat varchar(30),
 	listeRefMois t_listRefMois
 	);

/
--------------------------------------------------------
--  DDL for Type T_LISTREFMOIS
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_LISTREFMOIS" AS  TABLE  of t_refMois;

/
--------------------------------------------------------
--  DDL for Type T_BUDGETPROJET
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_BUDGETPROJET" AS object(
 	montantDemande number,
 	montantAttribue number,
 	montantExecute number,
 	montantRestant number,
 	listeTheme t_listeRefThemes
 	);

/
--------------------------------------------------------
--  DDL for Type T_LISTEREFTHEMES
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_LISTEREFTHEMES" AS  TABLE  of t_refTheme;

/
--------------------------------------------------------
--  DDL for Type T_CATEGORIEPROJET
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_CATEGORIEPROJET" as object(
	libelle varchar(20)
);

/
--------------------------------------------------------
--  DDL for Type T_ELEMENTPLANMENSUEL
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_ELEMENTPLANMENSUEL" AS object(
	code varchar(30),
	libelle varchar(30),
	montant number
 	);

/
--------------------------------------------------------
--  DDL for Type T_GROUPE_UTILISATEUR
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_GROUPE_UTILISATEUR" AS object(
	nom varchar(50),
	liste_privileges t_liste_t_ref_t_privilege
 	);

/
--------------------------------------------------------
--  DDL for Type T_LISTE_T_REF_T_PRIVILEGE
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_LISTE_T_REF_T_PRIVILEGE" AS  TABLE  of t_ref_t_privilege;

/
--------------------------------------------------------
--  DDL for Type T_LANGUE
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_LANGUE" as object(
	nom varchar(25), code varchar(10)
);

/
--------------------------------------------------------
--  DDL for Type T_LIGNEBUDGET
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_LIGNEBUDGET" AS object(
 	libelle varchar(30),
 	montantPrevu number,
 	montantExecute number
 	);

/
--------------------------------------------------------
--  DDL for Type T_REFELEMENTPLANMENSUEL
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_REFELEMENTPLANMENSUEL" AS object(
	valeur ref t_elementPlanMensuel
	);

/
--------------------------------------------------------
--  DDL for Type T_REFLIGNEBUDGET
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_REFLIGNEBUDGET" AS object (
	valeur ref t_ligneBudget
	);

/
--------------------------------------------------------
--  DDL for Type T_MOIS
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_MOIS" AS object(
 	code varchar(30),
 	libelle varchar(30),
 	etat varchar(30)
 	);

/
--------------------------------------------------------
--  DDL for Type T_REFMOIS
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_REFMOIS" AS object(
	valeur ref t_mois
	);

/
--------------------------------------------------------
--  DDL for Type T_PLANMENSUEL
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_PLANMENSUEL" AS object (
	code varchar(30),
	libelle varchar(30),
	refMois ref t_mois,
	listeRefElementPlanMensuel t_listeRefElementPlanMensuel
	);

/
--------------------------------------------------------
--  DDL for Type T_REFPLANMENSUEL
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_REFPLANMENSUEL" AS object (
	valeur ref t_planMensuel
	);

/
--------------------------------------------------------
--  DDL for Type T_REFTHEME
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_REFTHEME" AS object (
 	valeur ref t_themes
 	);

/
--------------------------------------------------------
--  DDL for Type T_THEMES
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_THEMES" AS object(
 	libelle varchar(30),
 	refActiveB t_refActiviteB
 	);

/
--------------------------------------------------------
--  DDL for Type T_MONNAIE
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_MONNAIE" as object(
	nomDevise varchar(20), 
	signe varchar(20)
);

/
--------------------------------------------------------
--  DDL for Type T_OPERATIONBANQUE
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_OPERATIONBANQUE" under t_Operation(
	typeOpBancaire varchar(50),
	referenceOperation varchar(50)
);

/
--------------------------------------------------------
--  DDL for Type T_OPERATIONCAISSE
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_OPERATIONCAISSE" under t_Operation(
	numRecu integer
);

/
--------------------------------------------------------
--  DDL for Type T_PAYS
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_PAYS" as object(
	codePays varchar(30),
	nomComplet varchar(30),
	nomAbrege varchar(30),
	langue REF t_langue,
	monnaie REF t_monnaie
);

/
--------------------------------------------------------
--  DDL for Type T_LISTEREFPLANMENSUEL
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_LISTEREFPLANMENSUEL" AS  TABLE  of t_refPlanMensuel;

/
--------------------------------------------------------
--  DDL for Type T_PLANANNUEL
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_PLANANNUEL" AS object (
	libelle varchar(30),
	code varchar(30),
	montamtTotalPrevu number,
	refAnneeComptable ref t_anneeComptable,
	refBudgetProjet ref t_budgetProjet,
	listePlanMensuel t_listeRefPlanMensuel
	);

/
--------------------------------------------------------
--  DDL for Type T_LISTEREFELEMENTPLANMENSUEL
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_LISTEREFELEMENTPLANMENSUEL" AS  TABLE  of t_refElementPlanMensuel;

/
--------------------------------------------------------
--  DDL for Type T_PRIVILEGE
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_PRIVILEGE" AS object(
	nom varchar(50),
	codePriv varchar(50)
 	)final;

/
--------------------------------------------------------
--  DDL for Type T_PROJET
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_PROJET" under t_structure(
	nomP varchar(50),
	secteur REF t_secteurActivite,
	categorie REF t_categorieProjet,
	villeProjet REF t_ville
);

/
--------------------------------------------------------
--  DDL for Type T_SECTEURACTIVITE
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_SECTEURACTIVITE" as object(
	libelle varchar(20),
	code varchar(20)
);

/
--------------------------------------------------------
--  DDL for Type T_VILLE
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_VILLE" as object(
	nomVille varchar(25),
	lePays ref t_pays
);

/
--------------------------------------------------------
--  DDL for Type T_STRUCTURE
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_STRUCTURE" AS object(
	nom varchar(100)
 	)not final ;

/
--------------------------------------------------------
--  DDL for Type T_REF_T_PRIVILEGE
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_REF_T_PRIVILEGE" AS object(
			valeur ref t_privilege
		);

/
--------------------------------------------------------
--  DDL for Type T_REFACTIVITEB
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_REFACTIVITEB" AS object (
 	valeur ref t_activiteB
 	);

/
--------------------------------------------------------
--  DDL for Type T_UTILISATEUR
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DARCIA"."T_UTILISATEUR" AS object(
	nom varchar(50),
	prenom varchar(100),
	email varchar(200),
	password varchar(100),
	profil varchar(50),
	groupe_utilisateur REF t_groupe_utilisateur,
	structure REF t_structure

 	);

/
--------------------------------------------------------
--  DDL for Table ACTIVEB
--------------------------------------------------------

  CREATE TABLE "DARCIA"."ACTIVEB" OF 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 NESTED TABLE "LISTREFLIGNEBUDGET" STORE AS "MESLIGNESBUDGETS"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) RETURN AS VALUE;
--------------------------------------------------------
--  DDL for Table ANNEECOMPTABLE
--------------------------------------------------------

  CREATE TABLE "DARCIA"."ANNEECOMPTABLE" OF "DARCIA"."T_ANNEECOMPTABLE" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 NESTED TABLE "LISTEREFMOIS" STORE AS "MESMOIS"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) RETURN AS VALUE;
--------------------------------------------------------
--  DDL for Table BUDGETPROJET
--------------------------------------------------------

  CREATE TABLE "DARCIA"."BUDGETPROJET" OF 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 NESTED TABLE "LISTETHEME" STORE AS "MESTHEMES"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) RETURN AS VALUE;
--------------------------------------------------------
--  DDL for Table CATEGORIEPROJET
--------------------------------------------------------

  CREATE TABLE "DARCIA"."CATEGORIEPROJET" OF "DARCIA"."T_CATEGORIEPROJET" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ELEMENTPLANMENSUEL
--------------------------------------------------------

  CREATE TABLE "DARCIA"."ELEMENTPLANMENSUEL" OF "DARCIA"."T_ELEMENTPLANMENSUEL" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GROUPES_UTILISATEUR
--------------------------------------------------------

  CREATE TABLE "DARCIA"."GROUPES_UTILISATEUR" OF "DARCIA"."T_GROUPE_UTILISATEUR" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 NESTED TABLE "LISTE_PRIVILEGES" STORE AS "TAB_PRIVILEGES"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) RETURN AS VALUE;
--------------------------------------------------------
--  DDL for Table LANGUE
--------------------------------------------------------

  CREATE TABLE "DARCIA"."LANGUE" OF "DARCIA"."T_LANGUE" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIGNEBUDGET
--------------------------------------------------------

  CREATE TABLE "DARCIA"."LIGNEBUDGET" OF "DARCIA"."T_LIGNEBUDGET" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
-- Impossible d'afficher le langage DDL TABLE pour l'objet DARCIA.MESELEMENTSPLANSMENSUELS avec DBMS_METADATA tentant le générateur interne.
CREATE TABLE MESELEMENTSPLANSMENSUELS 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCREATE INDEX SYS_FK0000022813N00006$ ON MESELEMENTSPLANSMENSUELS (NESTED_TABLE_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Impossible d'afficher le langage DDL TABLE pour l'objet DARCIA.MESLIGNESBUDGETS avec DBMS_METADATA tentant le générateur interne.
CREATE TABLE MESLIGNESBUDGETS 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCREATE INDEX SYS_FK0000022823N00007$ ON MESLIGNESBUDGETS (NESTED_TABLE_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Impossible d'afficher le langage DDL TABLE pour l'objet DARCIA.MESMOIS avec DBMS_METADATA tentant le générateur interne.
CREATE TABLE MESMOIS 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCREATE INDEX SYS_FK0000022818N00006$ ON MESMOIS (NESTED_TABLE_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Impossible d'afficher le langage DDL TABLE pour l'objet DARCIA.MESPLANMENSUEL avec DBMS_METADATA tentant le générateur interne.
CREATE TABLE MESPLANMENSUEL 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCREATE INDEX SYS_FK0000022835N00008$ ON MESPLANMENSUEL (NESTED_TABLE_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Impossible d'afficher le langage DDL TABLE pour l'objet DARCIA.MESTHEMES avec DBMS_METADATA tentant le générateur interne.
CREATE TABLE MESTHEMESCREATE INDEX SYS_FK0000022830N00007$ ON MESTHEMES (NESTED_TABLE_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
--------------------------------------------------------
--  DDL for Table MOIS
--------------------------------------------------------

  CREATE TABLE "DARCIA"."MOIS" OF "DARCIA"."T_MOIS" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MONNAIE
--------------------------------------------------------

  CREATE TABLE "DARCIA"."MONNAIE" OF "DARCIA"."T_MONNAIE" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OPERATIONBANQUE
--------------------------------------------------------

  CREATE TABLE "DARCIA"."OPERATIONBANQUE" OF "DARCIA"."T_OPERATIONBANQUE" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OPERATIONCAISSE
--------------------------------------------------------

  CREATE TABLE "DARCIA"."OPERATIONCAISSE" OF "DARCIA"."T_OPERATIONCAISSE" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAYS
--------------------------------------------------------

  CREATE TABLE "DARCIA"."PAYS" OF "DARCIA"."T_PAYS" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PLANANNUEL
--------------------------------------------------------

  CREATE TABLE "DARCIA"."PLANANNUEL" OF 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 NESTED TABLE "LISTEPLANMENSUEL" STORE AS "MESPLANMENSUEL"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) RETURN AS VALUE;
--------------------------------------------------------
--  DDL for Table PLANMENSUEL
--------------------------------------------------------

  CREATE TABLE "DARCIA"."PLANMENSUEL" OF "DARCIA"."T_PLANMENSUEL" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 NESTED TABLE "LISTEREFELEMENTPLANMENSUEL" STORE AS "MESELEMENTSPLANSMENSUELS"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) RETURN AS VALUE;
--------------------------------------------------------
--  DDL for Table PRIVILEGESAPP
--------------------------------------------------------

  CREATE TABLE "DARCIA"."PRIVILEGESAPP" OF "DARCIA"."T_PRIVILEGE" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROJET
--------------------------------------------------------

  CREATE TABLE "DARCIA"."PROJET" OF "DARCIA"."T_PROJET" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SECTEURACTIVITE
--------------------------------------------------------

  CREATE TABLE "DARCIA"."SECTEURACTIVITE" OF "DARCIA"."T_SECTEURACTIVITE" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STRUCTURES
--------------------------------------------------------

  CREATE TABLE "DARCIA"."STRUCTURES" OF "DARCIA"."T_STRUCTURE" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
-- Impossible d'afficher le langage DDL TABLE pour l'objet DARCIA.TAB_PRIVILEGES avec DBMS_METADATA tentant le générateur interne.
CREATE TABLE TAB_PRIVILEGES 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCREATE INDEX SYS_FK0000022586N00004$ ON TAB_PRIVILEGES (NESTED_TABLE_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
--------------------------------------------------------
--  DDL for Table THEMES
--------------------------------------------------------

  CREATE TABLE "DARCIA"."THEMES" OF 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UTILISATEURS
--------------------------------------------------------

  CREATE TABLE "DARCIA"."UTILISATEURS" OF "DARCIA"."T_UTILISATEUR" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VILLE
--------------------------------------------------------

  CREATE TABLE "DARCIA"."VILLE" OF "DARCIA"."T_VILLE" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DARCIA.ACTIVEB
SET DEFINE OFF;
REM INSERTING into DARCIA.ANNEECOMPTABLE
SET DEFINE OFF;
REM INSERTING into DARCIA.BUDGETPROJET
SET DEFINE OFF;
REM INSERTING into DARCIA.CATEGORIEPROJET
SET DEFINE OFF;
Insert into DARCIA.CATEGORIEPROJET (LIBELLE) values ('Construction');
Insert into DARCIA.CATEGORIEPROJET (LIBELLE) values ('Entrepreneuriat ');
Insert into DARCIA.CATEGORIEPROJET (LIBELLE) values ('Financement ');
Insert into DARCIA.CATEGORIEPROJET (LIBELLE) values ('Leadership');
Insert into DARCIA.CATEGORIEPROJET (LIBELLE) values ('Humanitaire');
REM INSERTING into DARCIA.ELEMENTPLANMENSUEL
SET DEFINE OFF;
Insert into DARCIA.ELEMENTPLANMENSUEL (CODE,LIBELLE,MONTANT) values ('cddf','shdkfjn',null);
Insert into DARCIA.ELEMENTPLANMENSUEL (CODE,LIBELLE,MONTANT) values ('cddf','shdkfjn',null);
Insert into DARCIA.ELEMENTPLANMENSUEL (CODE,LIBELLE,MONTANT) values ('cddf','shdkfjn',null);
Insert into DARCIA.ELEMENTPLANMENSUEL (CODE,LIBELLE,MONTANT) values ('kzfsjlfkj','kjlkj',null);
Insert into DARCIA.ELEMENTPLANMENSUEL (CODE,LIBELLE,MONTANT) values ('kzfsjlfkj','kjlkj',null);
Insert into DARCIA.ELEMENTPLANMENSUEL (CODE,LIBELLE,MONTANT) values ('kzfsjlfkj','kjlkj',null);
REM INSERTING into DARCIA.GROUPES_UTILISATEUR
SET DEFINE OFF;
Insert into DARCIA.GROUPES_UTILISATEUR (NOM,LISTE_PRIVILEGES) values ('gestionnaireprojet',DARCIA.T_LISTE_T_REF_T_PRIVILEGE());
Insert into DARCIA.GROUPES_UTILISATEUR (NOM,LISTE_PRIVILEGES) values ('administrateur',DARCIA.T_LISTE_T_REF_T_PRIVILEGE());
Insert into DARCIA.GROUPES_UTILISATEUR (NOM,LISTE_PRIVILEGES) values ('agentcontroleoxfam',DARCIA.T_LISTE_T_REF_T_PRIVILEGE());
Insert into DARCIA.GROUPES_UTILISATEUR (NOM,LISTE_PRIVILEGES) values ('agentvalidationoxfam',DARCIA.T_LISTE_T_REF_T_PRIVILEGE());
Insert into DARCIA.GROUPES_UTILISATEUR (NOM,LISTE_PRIVILEGES) values ('operateurprojet',DARCIA.T_LISTE_T_REF_T_PRIVILEGE());
REM INSERTING into DARCIA.LANGUE
SET DEFINE OFF;
Insert into DARCIA.LANGUE (NOM,CODE) values ('francais','fr');
Insert into DARCIA.LANGUE (NOM,CODE) values ('english','en');
Insert into DARCIA.LANGUE (NOM,CODE) values ('Francais','FR');
Insert into DARCIA.LANGUE (NOM,CODE) values ('English','ENG');
Insert into DARCIA.LANGUE (NOM,CODE) values ('Espanol','ESP');
Insert into DARCIA.LANGUE (NOM,CODE) values ('Arabe','ARA');
Insert into DARCIA.LANGUE (NOM,CODE) values ('Portuguese','POR');
REM INSERTING into DARCIA.LIGNEBUDGET
SET DEFINE OFF;
Insert into DARCIA.LIGNEBUDGET (LIBELLE,MONTANTPREVU,MONTANTEXECUTE) values ('jdfshkjsdhfkj',null,'44444555');
Insert into DARCIA.LIGNEBUDGET (LIBELLE,MONTANTPREVU,MONTANTEXECUTE) values ('jdfshkjsdhfkj',null,'44444555');
Insert into DARCIA.LIGNEBUDGET (LIBELLE,MONTANTPREVU,MONTANTEXECUTE) values ('jdfshkjsdhfkj',null,'44444555');
Insert into DARCIA.LIGNEBUDGET (LIBELLE,MONTANTPREVU,MONTANTEXECUTE) values ('jdfshkjsdhfkj',null,'554545');
Insert into DARCIA.LIGNEBUDGET (LIBELLE,MONTANTPREVU,MONTANTEXECUTE) values ('jdfshkjsdhfkj',null,'554545');
Insert into DARCIA.LIGNEBUDGET (LIBELLE,MONTANTPREVU,MONTANTEXECUTE) values ('jdfshkjsdhfkj',null,'554545');
REM INSERTING into DARCIA.MOIS
SET DEFINE OFF;
Insert into DARCIA.MOIS (CODE,LIBELLE,ETAT) values ('cddf','ghdskj','ouvert');
Insert into DARCIA.MOIS (CODE,LIBELLE,ETAT) values ('cddf','ghdskj','ouvert');
Insert into DARCIA.MOIS (CODE,LIBELLE,ETAT) values ('cddf','ghdskj','ouvert');
Insert into DARCIA.MOIS (CODE,LIBELLE,ETAT) values ('cddf','ghdskj','ouvert');
Insert into DARCIA.MOIS (CODE,LIBELLE,ETAT) values ('kzfsjlfkj','jhgjgj','ouvert');
Insert into DARCIA.MOIS (CODE,LIBELLE,ETAT) values ('kzfsjlfkj','jhgjgj','ouvert');
Insert into DARCIA.MOIS (CODE,LIBELLE,ETAT) values ('kzfsjlfkj','jhgjgj','ouvert');
Insert into DARCIA.MOIS (CODE,LIBELLE,ETAT) values ('kzfsjlfkj','jhgjgj','ouvert');
REM INSERTING into DARCIA.MONNAIE
SET DEFINE OFF;
Insert into DARCIA.MONNAIE (NOMDEVISE,SIGNE) values ('euro','e');
Insert into DARCIA.MONNAIE (NOMDEVISE,SIGNE) values ('dollars','$');
Insert into DARCIA.MONNAIE (NOMDEVISE,SIGNE) values ('cfa','cfa');
Insert into DARCIA.MONNAIE (NOMDEVISE,SIGNE) values ('FCFA','CFA');
Insert into DARCIA.MONNAIE (NOMDEVISE,SIGNE) values ('Euro','€');
Insert into DARCIA.MONNAIE (NOMDEVISE,SIGNE) values ('USDollar','$');
Insert into DARCIA.MONNAIE (NOMDEVISE,SIGNE) values ('Livres','£');
Insert into DARCIA.MONNAIE (NOMDEVISE,SIGNE) values ('Ouguiya','Oug');
REM INSERTING into DARCIA.OPERATIONBANQUE
SET DEFINE OFF;
Insert into DARCIA.OPERATIONBANQUE (ID,LIBELLE,DATEOPERATION,SOMMEOPERATION,NOTEOPERATION,ETATSOUMISSION,SOUMISSION,REFERENCEPAIEMENT,LIGNEBUDGET,TYPEOPBANCAIRE,REFERENCEOPERATION) values ('2','Operation2',to_date('28/12/90','DD/MM/RR'),'25000','noteOperation 1','etatSoumission 1','soumission 1','referencePaiement 2222','1','type 1','refOpe');
Insert into DARCIA.OPERATIONBANQUE (ID,LIBELLE,DATEOPERATION,SOMMEOPERATION,NOTEOPERATION,ETATSOUMISSION,SOUMISSION,REFERENCEPAIEMENT,LIGNEBUDGET,TYPEOPBANCAIRE,REFERENCEOPERATION) values ('169','gghh',null,'424242','655656',null,null,'3536','1','Type1','44444');
REM INSERTING into DARCIA.OPERATIONCAISSE
SET DEFINE OFF;
Insert into DARCIA.OPERATIONCAISSE (ID,LIBELLE,DATEOPERATION,SOMMEOPERATION,NOTEOPERATION,ETATSOUMISSION,SOUMISSION,REFERENCEPAIEMENT,LIGNEBUDGET,NUMRECU) values ('103','Operation1',to_date('28/12/82','DD/MM/RR'),'25000','noteOperation 1','etatSoumission 1','soumission 1','referencePaiement 2222','1','12550');
Insert into DARCIA.OPERATIONCAISSE (ID,LIBELLE,DATEOPERATION,SOMMEOPERATION,NOTEOPERATION,ETATSOUMISSION,SOUMISSION,REFERENCEPAIEMENT,LIGNEBUDGET,NUMRECU) values ('165','Operation1',to_date('28/12/82','DD/MM/RR'),'25000','noteOperation 1','etatSoumission 1','soumission 1','referencePaiement 2222','3','125');
Insert into DARCIA.OPERATIONCAISSE (ID,LIBELLE,DATEOPERATION,SOMMEOPERATION,NOTEOPERATION,ETATSOUMISSION,SOUMISSION,REFERENCEPAIEMENT,LIGNEBUDGET,NUMRECU) values ('166','Operation2',to_date('28/12/91','DD/MM/RR'),'25000','noteOperation 2','etatSoumission 2','soumission 2','referencePaiem ent 2222','1','125');
Insert into DARCIA.OPERATIONCAISSE (ID,LIBELLE,DATEOPERATION,SOMMEOPERATION,NOTEOPERATION,ETATSOUMISSION,SOUMISSION,REFERENCEPAIEMENT,LIGNEBUDGET,NUMRECU) values ('167','Operation3',to_date('28/12/15','DD/MM/RR'),'25000','noteOperation 3','etatSoumission 3','soumission 3','referencePaiem ent 2222','2','125');
Insert into DARCIA.OPERATIONCAISSE (ID,LIBELLE,DATEOPERATION,SOMMEOPERATION,NOTEOPERATION,ETATSOUMISSION,SOUMISSION,REFERENCEPAIEMENT,LIGNEBUDGET,NUMRECU) values ('168','Operation3',to_date('28/12/15','DD/MM/RR'),'25000','noteOperation 3','etatSoumission 3','soumission 3','referencePaiem ent 2222','3','125');
REM INSERTING into DARCIA.PAYS
SET DEFINE OFF;
Insert into DARCIA.PAYS (CODEPAYS,NOMCOMPLET,NOMABREGE,LANGUE,MONNAIE) values ('sn','senegal',null,null,null);
Insert into DARCIA.PAYS (CODEPAYS,NOMCOMPLET,NOMABREGE,LANGUE,MONNAIE) values ('ml','mali',null,null,null);
Insert into DARCIA.PAYS (CODEPAYS,NOMCOMPLET,NOMABREGE,LANGUE,MONNAIE) values ('gm','gambie',null,null,'DARCIA.T_MONNAIE(''euro'',''e'')');
Insert into DARCIA.PAYS (CODEPAYS,NOMCOMPLET,NOMABREGE,LANGUE,MONNAIE) values ('mauritanie','mn',null,null,'DARCIA.T_MONNAIE(''cfa'',''cfa'')');
Insert into DARCIA.PAYS (CODEPAYS,NOMCOMPLET,NOMABREGE,LANGUE,MONNAIE) values ('1','Sénégal','SEN',null,'DARCIA.T_MONNAIE(''FCFA'',''CFA'')');
Insert into DARCIA.PAYS (CODEPAYS,NOMCOMPLET,NOMABREGE,LANGUE,MONNAIE) values ('2','Mali','MAL',null,'DARCIA.T_MONNAIE(''FCFA'',''CFA'')');
Insert into DARCIA.PAYS (CODEPAYS,NOMCOMPLET,NOMABREGE,LANGUE,MONNAIE) values ('3','Mauritanie','MAUR','DARCIA.T_LANGUE(''Arabe'',''ARA'')','DARCIA.T_MONNAIE(''Ouguiya'',''Oug'')');
REM INSERTING into DARCIA.PLANANNUEL
SET DEFINE OFF;
REM INSERTING into DARCIA.PLANMENSUEL
SET DEFINE OFF;
REM INSERTING into DARCIA.PRIVILEGESAPP
SET DEFINE OFF;
Insert into DARCIA.PRIVILEGESAPP (NOM,CODEPRIV) values ('gerer_langue','admin');
Insert into DARCIA.PRIVILEGESAPP (NOM,CODEPRIV) values ('gerer_sauvegarde','admin');
Insert into DARCIA.PRIVILEGESAPP (NOM,CODEPRIV) values ('importer_budget','admin');
Insert into DARCIA.PRIVILEGESAPP (NOM,CODEPRIV) values ('gerer_utilisateur','admin');
Insert into DARCIA.PRIVILEGESAPP (NOM,CODEPRIV) values ('creer_projet','validation');
Insert into DARCIA.PRIVILEGESAPP (NOM,CODEPRIV) values ('modifier_projet','validation');
Insert into DARCIA.PRIVILEGESAPP (NOM,CODEPRIV) values ('supprimer_projet','validation');
Insert into DARCIA.PRIVILEGESAPP (NOM,CODEPRIV) values ('cloturer_ouvrir_plan_mensuel','validation');
Insert into DARCIA.PRIVILEGESAPP (NOM,CODEPRIV) values ('consulter_etat_financier','validation');
Insert into DARCIA.PRIVILEGESAPP (NOM,CODEPRIV) values ('gerer_etat_financier','validation');
Insert into DARCIA.PRIVILEGESAPP (NOM,CODEPRIV) values ('imprimer_etat_financier','validation');
Insert into DARCIA.PRIVILEGESAPP (NOM,CODEPRIV) values ('consulter_projet','controle');
Insert into DARCIA.PRIVILEGESAPP (NOM,CODEPRIV) values ('consulter_etat_caisse','controle');
Insert into DARCIA.PRIVILEGESAPP (NOM,CODEPRIV) values ('consulter_etat_banque','controle');
Insert into DARCIA.PRIVILEGESAPP (NOM,CODEPRIV) values ('accepter_rejeter_operation','controle');
Insert into DARCIA.PRIVILEGESAPP (NOM,CODEPRIV) values ('notifier_projet','controle');
REM INSERTING into DARCIA.PROJET
SET DEFINE OFF;
Insert into DARCIA.PROJET (NOM,NOMP,SECTEUR,CATEGORIE,VILLEPROJET) values ('creation d ecole bbb',null,'DARCIA.T_SECTEURACTIVITE(''Informatique'',''INF'')','DARCIA.T_CATEGORIEPROJET(''Construction'')','DARCIA.T_VILLE(''Dakar'',NULL)');
Insert into DARCIA.PROJET (NOM,NOMP,SECTEUR,CATEGORIE,VILLEPROJET) values ('code camp',null,'DARCIA.T_SECTEURACTIVITE(''Informatique'',''INF'')','DARCIA.T_CATEGORIEPROJET(''Construction'')','DARCIA.T_VILLE(''Bamako'',''oracle.sql.REF@af014b3b'')');
REM INSERTING into DARCIA.SECTEURACTIVITE
SET DEFINE OFF;
Insert into DARCIA.SECTEURACTIVITE (LIBELLE,CODE) values ('Informatique','INF');
Insert into DARCIA.SECTEURACTIVITE (LIBELLE,CODE) values ('Agriculture','AGRI');
Insert into DARCIA.SECTEURACTIVITE (LIBELLE,CODE) values ('Elevage','ELEV');
Insert into DARCIA.SECTEURACTIVITE (LIBELLE,CODE) values ('Peche','PECH');
Insert into DARCIA.SECTEURACTIVITE (LIBELLE,CODE) values ('sante',null);
Insert into DARCIA.SECTEURACTIVITE (LIBELLE,CODE) values ('education',null);
Insert into DARCIA.SECTEURACTIVITE (LIBELLE,CODE) values ('culture',null);
Insert into DARCIA.SECTEURACTIVITE (LIBELLE,CODE) values ('sport',null);
REM INSERTING into DARCIA.STRUCTURES
SET DEFINE OFF;
Insert into DARCIA.STRUCTURES (NOM) values ('oxfam');
Insert into DARCIA.STRUCTURES (NOM) values ('crent');
Insert into DARCIA.STRUCTURES (NOM) values ('esp');
REM INSERTING into DARCIA.THEMES
SET DEFINE OFF;
REM INSERTING into DARCIA.UTILISATEURS
SET DEFINE OFF;
Insert into DARCIA.UTILISATEURS (NOM,PRENOM,EMAIL,PASSWORD,PROFIL,GROUPE_UTILISATEUR,STRUCTURE) values ('Thiam','Alassane','administrateur@oxfam.sn','482f7629a2511d23ef4e958b13a5ba54bdba06f2','agentoxfam','DARCIA.T_GROUPE_UTILISATEUR(''administrateur''DARCIA.T_LISTE_T_REF_T_PRIVILEGE())','DARCIA.T_STRUCTURE(''oxfam'')');
Insert into DARCIA.UTILISATEURS (NOM,PRENOM,EMAIL,PASSWORD,PROFIL,GROUPE_UTILISATEUR,STRUCTURE) values ('Ngom','Mamadou Moustapha','controle@oxfam.sn','482f7629a2511d23ef4e958b13a5ba54bdba06f2','agentoxfam','DARCIA.T_GROUPE_UTILISATEUR(''agentcontroleoxfam''DARCIA.T_LISTE_T_REF_T_PRIVILEGE())','DARCIA.T_STRUCTURE(''oxfam'')');
Insert into DARCIA.UTILISATEURS (NOM,PRENOM,EMAIL,PASSWORD,PROFIL,GROUPE_UTILISATEUR,STRUCTURE) values ('Diop','Lamine','validation@oxfam.sn','482f7629a2511d23ef4e958b13a5ba54bdba06f2','agentoxfam','DARCIA.T_GROUPE_UTILISATEUR(''agentvalidationoxfam''DARCIA.T_LISTE_T_REF_T_PRIVILEGE())','DARCIA.T_STRUCTURE(''oxfam'')');
Insert into DARCIA.UTILISATEURS (NOM,PRENOM,EMAIL,PASSWORD,PROFIL,GROUPE_UTILISATEUR,STRUCTURE) values ('Gueye','OUsmane','gestionnaire@crent.sn','482f7629a2511d23ef4e958b13a5ba54bdba06f2','agentprojet','DARCIA.T_GROUPE_UTILISATEUR(''gestionnaireprojet''DARCIA.T_LISTE_T_REF_T_PRIVILEGE())','DARCIA.T_STRUCTURE(''crent'')');
Insert into DARCIA.UTILISATEURS (NOM,PRENOM,EMAIL,PASSWORD,PROFIL,GROUPE_UTILISATEUR,STRUCTURE) values ('Diouf','Doudou','operateur@crent.sn','482f7629a2511d23ef4e958b13a5ba54bdba06f2','agentprojet','DARCIA.T_GROUPE_UTILISATEUR(''operateurprojet''DARCIA.T_LISTE_T_REF_T_PRIVILEGE())','DARCIA.T_STRUCTURE(''crent'')');
Insert into DARCIA.UTILISATEURS (NOM,PRENOM,EMAIL,PASSWORD,PROFIL,GROUPE_UTILISATEUR,STRUCTURE) values ('nom','prenom','email','482f7629a2511d23ef4e958b13a5ba54bdba06f2','profil','DARCIA.T_GROUPE_UTILISATEUR(''administrateur''DARCIA.T_LISTE_T_REF_T_PRIVILEGE())','DARCIA.T_STRUCTURE(''oxfam'')');
Insert into DARCIA.UTILISATEURS (NOM,PRENOM,EMAIL,PASSWORD,PROFIL,GROUPE_UTILISATEUR,STRUCTURE) values ('nom','prenom','email','482f7629a2511d23ef4e958b13a5ba54bdba06f2','profil','DARCIA.T_GROUPE_UTILISATEUR(''administrateur''DARCIA.T_LISTE_T_REF_T_PRIVILEGE())','DARCIA.T_STRUCTURE(''oxfam'')');
Insert into DARCIA.UTILISATEURS (NOM,PRENOM,EMAIL,PASSWORD,PROFIL,GROUPE_UTILISATEUR,STRUCTURE) values (' khoussa',' darcia','darcia0001@gmail.com','482f7629a2511d23ef4e958b13a5ba54bdba06f2','agentoxfam','DARCIA.T_GROUPE_UTILISATEUR(''administrateur''DARCIA.T_LISTE_T_REF_T_PRIVILEGE())','DARCIA.T_STRUCTURE(''oxfam'')');
Insert into DARCIA.UTILISATEURS (NOM,PRENOM,EMAIL,PASSWORD,PROFIL,GROUPE_UTILISATEUR,STRUCTURE) values ('nom','prenom','email','482f7629a2511d23ef4e958b13a5ba54bdba06f2','profil','DARCIA.T_GROUPE_UTILISATEUR(''administrateur''DARCIA.T_LISTE_T_REF_T_PRIVILEGE())','DARCIA.T_STRUCTURE(''oxfam'')');
Insert into DARCIA.UTILISATEURS (NOM,PRENOM,EMAIL,PASSWORD,PROFIL,GROUPE_UTILISATEUR,STRUCTURE) values ('diallo','Yaya','gestionnaire@dgi.sn','482f7629a2511d23ef4e958b13a5ba54bdba06f2','agentprojet',null,'DARCIA.T_STRUCTURE(''crent'')');
Insert into DARCIA.UTILISATEURS (NOM,PRENOM,EMAIL,PASSWORD,PROFIL,GROUPE_UTILISATEUR,STRUCTURE) values ('jkhkjh',' ejfsdlkdj','email@esp.sn','482f7629a2511d23ef4e958b13a5ba54bdba06f2','agentprojet',null,'DARCIA.T_STRUCTURE(''esp'')');
REM INSERTING into DARCIA.VILLE
SET DEFINE OFF;
Insert into DARCIA.VILLE (NOMVILLE,LEPAYS) values ('saint louis','DARCIA.T_PAYS(''sn'',''senegal'',NULL,NULL,NULL)');
Insert into DARCIA.VILLE (NOMVILLE,LEPAYS) values ('Dakar',null);
Insert into DARCIA.VILLE (NOMVILLE,LEPAYS) values ('Tambacounda',null);
Insert into DARCIA.VILLE (NOMVILLE,LEPAYS) values ('Ziguinchor',null);
Insert into DARCIA.VILLE (NOMVILLE,LEPAYS) values ('Bamako','DARCIA.T_PAYS(''2'',''Mali'',''MAL'',NULL,''oracle.sql.REF@11c64c1d'')');
Insert into DARCIA.VILLE (NOMVILLE,LEPAYS) values ('Praia',null);
Insert into DARCIA.VILLE (NOMVILLE,LEPAYS) values ('Abidjan',null);
Insert into DARCIA.VILLE (NOMVILLE,LEPAYS) values ('Niamey',null);
Insert into DARCIA.VILLE (NOMVILLE,LEPAYS) values ('Nouatchok','DARCIA.T_PAYS(''3'',''Mauritanie'',''MAUR'',''oracle.sql.REF@1cd549c8'',''oracle.sql.REF@21314462'')');
Insert into DARCIA.VILLE (NOMVILLE,LEPAYS) values ('Lomé',null);
Insert into DARCIA.VILLE (NOMVILLE,LEPAYS) values ('Cotonou',null);
--------------------------------------------------------
--  DDL for Index SYS_C007319
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007319" ON "DARCIA"."ACTIVEB" ("SYS_NC0000700008$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007320
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007320" ON "DARCIA"."ACTIVEB" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007317
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007317" ON "DARCIA"."ANNEECOMPTABLE" ("SYS_NC0000600007$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007318
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007318" ON "DARCIA"."ANNEECOMPTABLE" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007322
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007322" ON "DARCIA"."BUDGETPROJET" ("SYS_NC0000700008$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007323
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007323" ON "DARCIA"."BUDGETPROJET" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007420
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007420" ON "DARCIA"."CATEGORIEPROJET" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007314
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007314" ON "DARCIA"."ELEMENTPLANMENSUEL" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007284
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007284" ON "DARCIA"."GROUPES_UTILISATEUR" ("SYS_NC0000400005$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007285
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007285" ON "DARCIA"."GROUPES_UTILISATEUR" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007418
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007418" ON "DARCIA"."LANGUE" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007328
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007328" ON "DARCIA"."LIGNEBUDGET" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_FK0000022813N00006$
--------------------------------------------------------

  CREATE INDEX "DARCIA"."SYS_FK0000022813N00006$" ON "DARCIA"."MESELEMENTSPLANSMENSUELS" ("NESTED_TABLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_FK0000022823N00007$
--------------------------------------------------------

  CREATE INDEX "DARCIA"."SYS_FK0000022823N00007$" ON "DARCIA"."MESLIGNESBUDGETS" ("NESTED_TABLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_FK0000022818N00006$
--------------------------------------------------------

  CREATE INDEX "DARCIA"."SYS_FK0000022818N00006$" ON "DARCIA"."MESMOIS" ("NESTED_TABLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_FK0000022835N00008$
--------------------------------------------------------

  CREATE INDEX "DARCIA"."SYS_FK0000022835N00008$" ON "DARCIA"."MESPLANMENSUEL" ("NESTED_TABLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_FK0000022830N00007$
--------------------------------------------------------

  CREATE INDEX "DARCIA"."SYS_FK0000022830N00007$" ON "DARCIA"."MESTHEMES" ("NESTED_TABLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007313
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007313" ON "DARCIA"."MOIS" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007417
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007417" ON "DARCIA"."MONNAIE" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007437
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007437" ON "DARCIA"."OPERATIONBANQUE" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007436
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007436" ON "DARCIA"."OPERATIONCAISSE" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007423
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007423" ON "DARCIA"."PAYS" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007324
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007324" ON "DARCIA"."PLANANNUEL" ("SYS_NC0000800009$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007325
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007325" ON "DARCIA"."PLANANNUEL" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007315
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007315" ON "DARCIA"."PLANMENSUEL" ("SYS_NC0000600007$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007316
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007316" ON "DARCIA"."PLANMENSUEL" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007283
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007283" ON "DARCIA"."PRIVILEGESAPP" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007422
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007422" ON "DARCIA"."PROJET" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007419
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007419" ON "DARCIA"."SECTEURACTIVITE" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007425
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007425" ON "DARCIA"."STRUCTURES" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_FK0000022586N00004$
--------------------------------------------------------

  CREATE INDEX "DARCIA"."SYS_FK0000022586N00004$" ON "DARCIA"."TAB_PRIVILEGES" ("NESTED_TABLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007321
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007321" ON "DARCIA"."THEMES" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007424
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007424" ON "DARCIA"."UTILISATEURS" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007421
--------------------------------------------------------

  CREATE UNIQUE INDEX "DARCIA"."SYS_C007421" ON "DARCIA"."VILLE" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ACTIVEB
--------------------------------------------------------

  ALTER TABLE "DARCIA"."ACTIVEB" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DARCIA"."ACTIVEB" ADD UNIQUE ("LISTREFLIGNEBUDGET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ANNEECOMPTABLE
--------------------------------------------------------

  ALTER TABLE "DARCIA"."ANNEECOMPTABLE" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DARCIA"."ANNEECOMPTABLE" ADD UNIQUE ("LISTEREFMOIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BUDGETPROJET
--------------------------------------------------------

  ALTER TABLE "DARCIA"."BUDGETPROJET" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DARCIA"."BUDGETPROJET" ADD UNIQUE ("LISTETHEME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIEPROJET
--------------------------------------------------------

  ALTER TABLE "DARCIA"."CATEGORIEPROJET" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ELEMENTPLANMENSUEL
--------------------------------------------------------

  ALTER TABLE "DARCIA"."ELEMENTPLANMENSUEL" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GROUPES_UTILISATEUR
--------------------------------------------------------

  ALTER TABLE "DARCIA"."GROUPES_UTILISATEUR" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DARCIA"."GROUPES_UTILISATEUR" ADD UNIQUE ("LISTE_PRIVILEGES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LANGUE
--------------------------------------------------------

  ALTER TABLE "DARCIA"."LANGUE" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIGNEBUDGET
--------------------------------------------------------

  ALTER TABLE "DARCIA"."LIGNEBUDGET" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MOIS
--------------------------------------------------------

  ALTER TABLE "DARCIA"."MOIS" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MONNAIE
--------------------------------------------------------

  ALTER TABLE "DARCIA"."MONNAIE" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OPERATIONBANQUE
--------------------------------------------------------

  ALTER TABLE "DARCIA"."OPERATIONBANQUE" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OPERATIONCAISSE
--------------------------------------------------------

  ALTER TABLE "DARCIA"."OPERATIONCAISSE" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYS
--------------------------------------------------------

  ALTER TABLE "DARCIA"."PAYS" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLANANNUEL
--------------------------------------------------------

  ALTER TABLE "DARCIA"."PLANANNUEL" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DARCIA"."PLANANNUEL" ADD UNIQUE ("LISTEPLANMENSUEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLANMENSUEL
--------------------------------------------------------

  ALTER TABLE "DARCIA"."PLANMENSUEL" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DARCIA"."PLANMENSUEL" ADD UNIQUE ("LISTEREFELEMENTPLANMENSUEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRIVILEGESAPP
--------------------------------------------------------

  ALTER TABLE "DARCIA"."PRIVILEGESAPP" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROJET
--------------------------------------------------------

  ALTER TABLE "DARCIA"."PROJET" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SECTEURACTIVITE
--------------------------------------------------------

  ALTER TABLE "DARCIA"."SECTEURACTIVITE" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STRUCTURES
--------------------------------------------------------

  ALTER TABLE "DARCIA"."STRUCTURES" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table THEMES
--------------------------------------------------------

  ALTER TABLE "DARCIA"."THEMES" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UTILISATEURS
--------------------------------------------------------

  ALTER TABLE "DARCIA"."UTILISATEURS" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VILLE
--------------------------------------------------------

  ALTER TABLE "DARCIA"."VILLE" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
